openapi: 3.0.3
info:
  title: Selectra サーバーサイドAPI定義書
  version: 0.1.1
paths:
  /matching/list:
    get:
      summary: マッチング診断の一覧に必要な情報の取得
      responses:
        200:
          description: マッチング診断の一覧に必要な情報の取得が成功する
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    matchingId:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    createdAt:
                      type: string
                    userName:
                      type: string
  /matching/match:
    get:
      summary: マッチング診断を始めるのに必要な情報の取得
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                matchingId:
                  type: string
      responses:
        200:
          description: マッチング診断を始めるのに必要な情報の取得が成功する
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  userName:
                    type: string
                  description:
                    type: string
                  paramsName:
                    type: array
                    items:
                      type: string
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        question:
                          type: string
                        choices:
                          type: array
                          items:
                            type: object
                            properties:
                              choiceId:
                                type: number
                              choiceName:
                                type: string
                              paramChanges:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    targetParamName:
                                      type: string
                                    changeValues:
                                      type: number

  /matching/result_output:
    get:
      summary: マッチング結果を取得
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                matchingId:
                  type: string
                choiceParams:
                  type: object
                  properties:
                    choiceId:
                      type: number
                    value:
                      type: number
      responses:
        200:
          description: マッチング結果の取得に成功する
          content:
            application/json:
              schema:
                type: object
                properties:
                  matchingTarget:
                    type: string
                  url:
                    type: string


  /matching/post:
    post:
      summary: マッチングに必要な情報の登録
      requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  userName:
                    type: string
                  description:
                    type: string
                  paramsName:
                    type: array
                    items:
                      type: string
                  url:
                    type: string
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        question:
                          type: string
                        choices:
                          type: array
                          items:
                            type: object
                            properties:
                              choiceId:
                                type: number
                              choiceName:
                                type: string
                              paramChanges:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    targetParamName:
                                      type: string
                                    changeValues:
                                      type: number
      responses:
        200:
          description: マッチングに必要な情報の投稿成功
